### ISSUE TITLE
Support JUEL and javascript

### ISSUE THREAD

**Issue by Yambr** [camunda-community-hub/camunda-dmn-tester#2]
Hey ! will be language support besides feel? 
JUEL and Javascript for example&

**Comment by pme123** [comment]
Hi @Yambr 

Sadly the DMN Tester works on top of the[ dmn-scala Engine](https://github.com/camunda-community-hub/dmn-scala). And this engine only supports FEEL.

See here https://forum.camunda.io/t/zeebe-dmn-worker-literal-expression-in-javascript-not-supported/2159
